### ISSUE TITLE
Demo4中set(EXTRA_LIBS ${EXTRA_LIBS} MathFunctions)看不懂

### ISSUE THREAD

**Issue by KongJHong** [wzpan/cmake-demo#5]
```cmake
if(USE_MYMATH)
    include_directories("${PROJECT_SOURCE_DIR}/math")
    add_subdirectory(math)
    set(EXTRA_LIBS ${EXTRA_LIBS} MathFunctions)
endif(USE_MYMATH)
```
这里面的`set(EXTRA_LIBS ${EXTRA_LIBS} MathFunctions)`看不懂
set(参数1 [参数2] [参数3] ...)
按理所应该是参数2是值，参数1是变量名
当set设置列表时，后面可以设置多个参数没错，参数1时变量名，参数2~n是值
这里的`EXTRA_LIBS`和`${EXTRA_LIBS}`看不懂，`${EXTRA_LIBS}`没声明过，不应该是空吗？这里写有什么意义？

**Comment by wzpan** [comment]
这就跟 shell 里：

``` bash
exports PATH=${PATH}:/my_custom_folder
```

一样。如果 `$PATH` 已经有定义，就追加多一个目录；如果没有定义，就把 `my_custom_folder` 作为值。

**Comment by KongJHong** [comment]
感谢博主讲解
